"""Skippy NPU sizer — interactive projection tool.

Lets a user:
  - Pick one of Skippy's models (dense 14B vs MoE 30B-A3B)
  - Pick an NPU tier (LOW_LP4 … HIGH) or select RTX 5090 reference
  - Pick a workload profile (short_chat, rag_qa, long_decode,
    meeting_summarization, agentic_roundtrip)
  - Tune a compiler-quality slider (0.5–1.0)
  - See measured (green badge) or BW-projected (yellow badge) numbers.

Password gate via st.secrets['PASSWORD']. Data source: sizer/sizer_bundle.json
(regenerated by personal-ai-framework's eval/build_sizer_bundle.py).
"""
from __future__ import annotations

import io

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from sizer.measured import get_bundle_summary
from sizer.npu_model import MODELS, TIERS, project_llm, model_active_bytes_per_token


st.set_page_config(page_title="Skippy NPU Sizer", layout="wide",
                   initial_sidebar_state="expanded")


# ───────────────────────── Password gate ─────────────────────────

def _gate() -> bool:
    want = st.secrets.get("PASSWORD") if hasattr(st, "secrets") else None
    if not want:
        return True  # no gate configured
    if st.session_state.get("_ok"):
        return True
    with st.form("login"):
        pw = st.text_input("Password", type="password", key="pw_input")
        if st.form_submit_button("Enter"):
            if pw == want:
                st.session_state["_ok"] = True
                st.rerun()
            else:
                st.error("Incorrect.")
    return False


if not _gate():
    st.stop()


# ───────────────────────── Workload profile metadata ─────────────────────────

# What-if prompt/decode shapes per workload profile. Mirrors the targets in
# eval/sizer_workload_profiles.json (personal-ai-framework). Users adjust
# these knobs in the sidebar; defaults match the profile's target shape.
WORKLOAD_DEFAULTS = {
    "short_chat":             {"prompt_tokens": 750,  "decode_tokens": 150,  "label": "Short chat — no RAG, conversational"},
    "rag_qa":                 {"prompt_tokens": 4800, "decode_tokens": 400,  "label": "RAG Q&A — retrieved context 5–10 chunks"},
    "long_decode":            {"prompt_tokens": 2800, "decode_tokens": 2500, "label": "Long-decode doc gen — spec / proposal"},
    "meeting_summarization":  {"prompt_tokens": 12700,"decode_tokens": 800,  "label": "Meeting summarization — 30–60 min transcript"},
    "agentic_roundtrip":      {"prompt_tokens": 2500, "decode_tokens": 200,  "label": "Agentic roundtrip — single tool-loop iteration"},
}


# ───────────────────────── Sidebar ─────────────────────────

with st.sidebar:
    st.header("Skippy NPU Sizer")

    st.caption("What-if perf model for Skippy on different NPU tiers. "
               "Measured baseline: RTX 5090 bake-offs from "
               "personal-ai-framework `eval/run_sizer_bakeoffs.py`.")

    model_keys = list(MODELS.keys())
    model_key = st.selectbox(
        "Model",
        options=model_keys,
        format_func=lambda k: MODELS[k]["display_name"],
        index=model_keys.index("qwen3-30b-a3b-q4-moe"),
        key="k_model",
        help="MoE decode tok/s scales with active params (~3B) not total "
             "params (~30B). Dense 14B moves ~5× more bytes per decoded token.",
    )

    tier_keys = list(TIERS.keys())
    tier_name = st.selectbox(
        "NPU Tier",
        options=tier_keys,
        index=tier_keys.index("NPU Mid"),
        key="k_tier",
        help="RTX 5090 shows measured Skippy data. All NPU tiers project "
             "from the 5090 baseline by effective-bandwidth ratio.",
    )
    hw = TIERS[tier_name]

    workload_keys = list(WORKLOAD_DEFAULTS.keys())
    workload_id = st.selectbox(
        "Workload profile",
        options=workload_keys,
        format_func=lambda k: WORKLOAD_DEFAULTS[k]["label"],
        index=0,
        key="k_workload",
    )

    with st.expander("Per-workload token shape", expanded=False):
        wd = WORKLOAD_DEFAULTS[workload_id]
        prompt_tokens = st.number_input(
            "Prompt tokens",
            min_value=10, max_value=128000,
            value=wd["prompt_tokens"], step=100,
            key=f"k_pt_{workload_id}",
        )
        decode_tokens = st.number_input(
            "Decode tokens",
            min_value=1, max_value=8000,
            value=wd["decode_tokens"], step=50,
            key=f"k_dt_{workload_id}",
        )

    compiler_quality = st.slider(
        "Compiler quality",
        min_value=0.5, max_value=1.0, value=1.0, step=0.05,
        key="k_compiler",
        help="How well the target NPU's compiler stack matches NVIDIA's mature "
             "CUDA path. 1.0 = parity; 0.5 = half the throughput at same BW. "
             "Only applied to projected tiers, not measured.",
    )

    with st.expander("About this sizer", expanded=False):
        bs = get_bundle_summary()
        st.caption(
            f"Bundle generated: {bs['bundle_meta'].get('generated_at','?')}\n\n"
            f"Models measured: {len(bs['models'])}\n\n"
            f"Source bake-offs: see `sizer_bundle.json` meta."
        )


# ───────────────────────── Main page ─────────────────────────

st.title(f"{MODELS[model_key]['display_name']} · {tier_name}")
st.caption(f"Workload: _{WORKLOAD_DEFAULTS[workload_id]['label']}_ — "
           f"{prompt_tokens:,} prompt / {decode_tokens:,} decode tokens")


# Project the selected cell
try:
    r = project_llm(
        model_key, hw, workload_id,
        prompt_tokens=prompt_tokens,
        decode_tokens=decode_tokens,
        compiler_quality=compiler_quality,
    )
    err = None
except ValueError as e:
    r, err = None, str(e)

if err:
    st.error(f"No projection available: {err}")
    st.stop()

# Top-line results row
badge = ("🟢 measured" if r["source"] == "measured"
         else "🟡 projected (BW-scaled from RTX 5090)")
c1, c2, c3, c4, c5 = st.columns(5)
c1.metric("Source", badge)
c2.metric("Decode tok/s", f"{r['decode_tok_s']:.1f}")
c3.metric("Prefill tok/s", f"{r['prefill_tok_s']:,.0f}")
c4.metric("Total latency", f"{r['total_s']:.2f}s")
c5.metric("Decode time", f"{r['decode_s']:.2f}s")

st.markdown("---")

# Per-stage breakdown bar chart
stage_ms = {
    "Host (retrieval + agent)": r["host_ms"],
    "Prefill": r["prefill_s"] * 1000,
    "Decode": r["decode_s"] * 1000,
}
fig = go.Figure()
fig.add_trace(go.Bar(
    x=list(stage_ms.keys()),
    y=list(stage_ms.values()),
    text=[f"{v:,.0f} ms" for v in stage_ms.values()],
    textposition="outside",
    marker_color=["#6b7280", "#3b82f6", "#10b981"],
))
fig.update_layout(
    title=f"Per-stage time — {MODELS[model_key]['display_name']} / {tier_name}",
    yaxis_title="Milliseconds (log)",
    yaxis_type="log",
    height=380,
    plot_bgcolor="#1f2937",
    paper_bgcolor="#111827",
    font=dict(color="#f3f4f6"),
    xaxis=dict(showgrid=False),
    yaxis=dict(gridcolor="#374151"),
)
st.plotly_chart(fig, use_container_width=True)


# Cross-tier comparison table
st.subheader("Cross-tier comparison")
rows = []
for tname, thw in TIERS.items():
    try:
        rr = project_llm(
            model_key, thw, workload_id,
            prompt_tokens=prompt_tokens,
            decode_tokens=decode_tokens,
            compiler_quality=compiler_quality,
        )
        rows.append({
            "tier": tname,
            "source": rr["source"],
            "decode_tok_s": rr["decode_tok_s"],
            "prefill_tok_s": rr["prefill_tok_s"],
            "total_s": rr["total_s"],
            "prefill_s": rr["prefill_s"],
            "decode_s": rr["decode_s"],
            "host_ms": rr["host_ms"],
        })
    except ValueError:
        rows.append({"tier": tname, "source": "no_data"})
df = pd.DataFrame(rows)
st.dataframe(df, use_container_width=True, hide_index=True)


# Cross-model comparison on this tier
st.subheader("Cross-model comparison (on this tier)")
rows2 = []
for mk in MODELS:
    try:
        rr = project_llm(
            mk, hw, workload_id,
            prompt_tokens=prompt_tokens,
            decode_tokens=decode_tokens,
            compiler_quality=compiler_quality,
        )
        rows2.append({
            "model": MODELS[mk]["display_name"],
            "is_moe": MODELS[mk]["is_moe"],
            "active_params_B": round(MODELS[mk]["active_params"] / 1e9, 1),
            "bytes_per_tok_decode_B": round(model_active_bytes_per_token(mk) / 1e9, 2),
            "decode_tok_s": rr["decode_tok_s"],
            "total_s": rr["total_s"],
            "source": rr["source"],
        })
    except ValueError:
        rows2.append({"model": MODELS[mk]["display_name"], "source": "no_data"})
df2 = pd.DataFrame(rows2)
st.dataframe(df2, use_container_width=True, hide_index=True)


# XLSX download
st.markdown("---")
buf = io.BytesIO()
with pd.ExcelWriter(buf, engine="openpyxl") as xlw:
    df.to_excel(xlw, sheet_name="cross_tier", index=False)
    df2.to_excel(xlw, sheet_name="cross_model", index=False)
st.download_button(
    "⬇ Download projections (XLSX)",
    data=buf.getvalue(),
    file_name=f"skippy_sizer_{model_key}_{tier_name.replace(' ','_')}_{workload_id}.xlsx",
    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
)


# Measured provenance panel
with st.expander("Measured data provenance", expanded=False):
    bs = get_bundle_summary()
    st.write("**Bundle metadata**")
    st.json(bs["bundle_meta"])
    st.write("**Per-model measured workloads**")
    st.json(bs["workloads_per_model"])
