"""Skippy NPU sizer — interactive projection tool.

Lets a user:
  - Pick one of Skippy's models (dense 14B vs MoE 30B-A3B)
  - Pick an NPU tier (LOW_LP4 … HIGH) or select RTX 5090 reference
  - Pick a workload profile (short_chat, rag_qa, long_decode,
    meeting_summarization, agentic_roundtrip)
  - Tune a compiler-quality slider (0.5–1.0)
  - See measured (green badge) or BW-projected (yellow badge) numbers.

Password gate via st.secrets['PASSWORD']. Data source: sizer/sizer_bundle.json
(regenerated by personal-ai-framework's eval/build_sizer_bundle.py).
"""
from __future__ import annotations

import io

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from sizer.measured import get_bundle_summary
from sizer.npu_model import MODELS, TIERS, project_llm, model_active_bytes_per_token


st.set_page_config(page_title="Skippy NPU Sizer", layout="wide",
                   initial_sidebar_state="expanded")


# ───────────────────────── Password gate ─────────────────────────

def _gate() -> bool:
    want = st.secrets.get("PASSWORD") if hasattr(st, "secrets") else None
    if not want:
        return True  # no gate configured
    if st.session_state.get("_ok"):
        return True
    with st.form("login"):
        pw = st.text_input("Password", type="password", key="pw_input")
        if st.form_submit_button("Enter"):
            if pw == want:
                st.session_state["_ok"] = True
                st.rerun()
            else:
                st.error("Incorrect.")
    return False


if not _gate():
    st.stop()


# ───────────────────────── Workload profile metadata ─────────────────────────

# What-if prompt/decode shapes per workload profile. Mirrors the targets in
# eval/sizer_workload_profiles.json (personal-ai-framework). Users adjust
# these knobs in the sidebar; defaults match the profile's target shape.
WORKLOAD_DEFAULTS = {
    "short_chat":             {"prompt_tokens": 750,  "decode_tokens": 150,  "label": "Short chat — no RAG, conversational"},
    "rag_qa":                 {"prompt_tokens": 4800, "decode_tokens": 400,  "label": "RAG Q&A — retrieved context 5–10 chunks"},
    "long_decode":            {"prompt_tokens": 2800, "decode_tokens": 2500, "label": "Long-decode doc gen — spec / proposal"},
    "meeting_summarization":  {"prompt_tokens": 12700,"decode_tokens": 800,  "label": "Meeting summarization — 30–60 min transcript"},
    "agentic_roundtrip":      {"prompt_tokens": 2500, "decode_tokens": 200,  "label": "Agentic roundtrip — single tool-loop iteration"},
}


# ───────────────────────── Sidebar ─────────────────────────

with st.sidebar:
    st.header("Skippy NPU Sizer")

    st.caption("What-if perf model for Skippy on different NPU tiers. "
               "Measured baseline: RTX 5090 bake-offs from "
               "personal-ai-framework `eval/run_sizer_bakeoffs.py`.")

    model_keys = list(MODELS.keys())
    model_key = st.selectbox(
        "Model",
        options=model_keys,
        format_func=lambda k: MODELS[k]["display_name"],
        index=model_keys.index("qwen3-30b-a3b-q4-moe"),
        key="k_model",
        help="MoE decode tok/s scales with active params (~3B) not total "
             "params (~30B). Dense 14B moves ~5× more bytes per decoded token.",
    )

    tier_keys = list(TIERS.keys())
    tier_name = st.selectbox(
        "NPU Tier",
        options=tier_keys,
        index=tier_keys.index("NPU Mid"),
        key="k_tier",
        help="RTX 5090 shows measured Skippy data. All NPU tiers project "
             "from the 5090 baseline by effective-bandwidth ratio.",
    )
    hw = TIERS[tier_name]

    workload_keys = list(WORKLOAD_DEFAULTS.keys())
    workload_id = st.selectbox(
        "Workload profile",
        options=workload_keys,
        format_func=lambda k: WORKLOAD_DEFAULTS[k]["label"],
        index=0,
        key="k_workload",
    )

    with st.expander("Per-workload token shape", expanded=False):
        wd = WORKLOAD_DEFAULTS[workload_id]
        prompt_tokens = st.number_input(
            "Prompt tokens",
            min_value=10, max_value=128000,
            value=wd["prompt_tokens"], step=100,
            key=f"k_pt_{workload_id}",
        )
        decode_tokens = st.number_input(
            "Decode tokens",
            min_value=1, max_value=8000,
            value=wd["decode_tokens"], step=50,
            key=f"k_dt_{workload_id}",
        )

    compiler_quality = st.slider(
        "Compiler quality",
        min_value=0.5, max_value=1.0, value=1.0, step=0.05,
        key="k_compiler",
        help="How well the target NPU's compiler stack matches NVIDIA's mature "
             "CUDA path. 1.0 = parity; 0.5 = half the throughput at same BW. "
             "Only applied to projected tiers, not measured.",
    )

    with st.expander("About this sizer", expanded=False):
        bs = get_bundle_summary()
        st.caption(
            f"Bundle generated: {bs['bundle_meta'].get('generated_at','?')}\n\n"
            f"Models measured: {len(bs['models'])}\n\n"
            f"Source bake-offs: see `sizer_bundle.json` meta."
        )


# ───────────────────────── Main page ─────────────────────────

st.title(MODELS[model_key]['display_name'])
st.markdown(f"**Tier:** {tier_name}  &nbsp;·&nbsp;  **Workload:** "
            f"_{WORKLOAD_DEFAULTS[workload_id]['label']}_  &nbsp;·&nbsp;  "
            f"{prompt_tokens:,} prompt / {decode_tokens:,} decode tokens")


# Project the selected cell
try:
    r = project_llm(
        model_key, hw, workload_id,
        prompt_tokens=prompt_tokens,
        decode_tokens=decode_tokens,
        compiler_quality=compiler_quality,
    )
    err = None
except ValueError as e:
    r, err = None, str(e)

if err:
    st.warning(
        f"**No measurement yet for this cell.** Run "
        f"`eval/run_sizer_bakeoffs.py` against a Skippy instance, "
        f"regenerate `sizer_bundle.json`, and redeploy. Detail: {err}"
    )
    st.stop()

# Source badge (rendered as a styled line, not a metric — long text truncates)
if r["source"] == "measured":
    st.success(f"🟢 **Measured** on RTX 5090 — direct bake-off baseline")
else:
    st.info(f"🟡 **Projected** — BW-scaled from RTX 5090 reference. "
            f"Effective-bandwidth ratio: {hw.effective_bandwidth_gbs / 1523.2:.3f}")

# Top-line numeric metrics
c1, c2, c3, c4 = st.columns(4)
c1.metric("Decode tok/s", f"{r['decode_tok_s']:.1f}")
c2.metric("Prefill tok/s", f"{r['prefill_tok_s']:.0f}")
c3.metric("Total latency", f"{r['total_s']:.2f} s")
c4.metric("Decode portion", f"{r['decode_s']:.2f} s")

st.markdown("---")

# Per-stage breakdown bar chart
stage_ms = {
    "Host (retrieval + agent)": r["host_ms"],
    "Prefill": r["prefill_s"] * 1000,
    "Decode": r["decode_s"] * 1000,
}
fig = go.Figure()
fig.add_trace(go.Bar(
    x=list(stage_ms.keys()),
    y=list(stage_ms.values()),
    text=[f"{v:,.0f} ms" for v in stage_ms.values()],
    textposition="outside",
    marker_color=["#6b7280", "#3b82f6", "#10b981"],
))
import math
_ymax = max(stage_ms.values())
fig.update_layout(
    title=f"Per-stage time — {MODELS[model_key]['display_name']} / {tier_name}",
    yaxis_title="Milliseconds (log)",
    yaxis_type="log",
    # Log-scale range: from 1ms to 1 decade above the tallest bar, so the
    # "outside" text labels don't clip against the top edge.
    yaxis=dict(gridcolor="#374151",
               range=[0, math.log10(max(_ymax, 10)) + 0.6]),
    height=420,
    margin=dict(t=60, b=40, l=40, r=20),
    plot_bgcolor="#1f2937",
    paper_bgcolor="#111827",
    font=dict(color="#f3f4f6"),
    xaxis=dict(showgrid=False),
)
st.plotly_chart(fig, width="stretch")


# Cross-tier comparison table
st.subheader("Cross-tier comparison")
st.caption(f"All tiers projected from RTX 5090's measured baseline for "
           f"**{MODELS[model_key]['display_name']}** at **{WORKLOAD_DEFAULTS[workload_id]['label']}**. "
           "Lower tier → more bandwidth-bound → slower decode.")
rows = []
for tname, thw in TIERS.items():
    try:
        rr = project_llm(
            model_key, thw, workload_id,
            prompt_tokens=prompt_tokens,
            decode_tokens=decode_tokens,
            compiler_quality=compiler_quality,
        )
        rows.append({
            "Tier": tname,
            "Source": "🟢 measured" if rr["source"] == "measured" else "🟡 projected",
            "Decode tok/s": rr["decode_tok_s"],
            "Prefill tok/s": round(rr["prefill_tok_s"]),
            "Total (s)": rr["total_s"],
            "Host (ms)": rr["host_ms"],
        })
    except ValueError:
        rows.append({"Tier": tname, "Source": "⚪ no data"})
df = pd.DataFrame(rows)
st.dataframe(df, width="stretch", hide_index=True)


# Cross-model comparison on this tier
st.subheader("Cross-model comparison (on this tier)")
st.caption("MoE's decode advantage comes from fewer active params per token — "
           "dense 14B moves ~4.5× more weight bytes per decoded token than MoE 30B-A3B.")
rows2 = []
for mk in MODELS:
    try:
        rr = project_llm(
            mk, hw, workload_id,
            prompt_tokens=prompt_tokens,
            decode_tokens=decode_tokens,
            compiler_quality=compiler_quality,
        )
        rows2.append({
            "Model": MODELS[mk]["display_name"],
            "Arch": "MoE" if MODELS[mk]["is_moe"] else "dense",
            "Active params (B)": round(MODELS[mk]["active_params"] / 1e9, 1),
            "Bytes/token decode (B)": round(model_active_bytes_per_token(mk) / 1e9, 2),
            "Decode tok/s": rr["decode_tok_s"],
            "Total (s)": rr["total_s"],
            "Source": "🟢 measured" if rr["source"] == "measured" else "🟡 projected",
        })
    except ValueError:
        rows2.append({"Model": MODELS[mk]["display_name"], "Source": "⚪ no data"})
df2 = pd.DataFrame(rows2)
st.dataframe(df2, width="stretch", hide_index=True)


# XLSX download
st.markdown("---")
buf = io.BytesIO()
with pd.ExcelWriter(buf, engine="openpyxl") as xlw:
    df.to_excel(xlw, sheet_name="cross_tier", index=False)
    df2.to_excel(xlw, sheet_name="cross_model", index=False)
st.download_button(
    "⬇ Download projections (XLSX)",
    data=buf.getvalue(),
    file_name=f"skippy_sizer_{model_key}_{tier_name.replace(' ','_')}_{workload_id}.xlsx",
    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
)


# Measured provenance panel
with st.expander("Measured data provenance", expanded=False):
    bs = get_bundle_summary()
    st.write("**Bundle metadata**")
    st.json(bs["bundle_meta"])
    st.write("**Per-model measured workloads**")
    st.json(bs["workloads_per_model"])
