"""Skippy NPU sizer — interactive projection tool.

Lets a user:
  - Pick one of Skippy's models (dense 14B vs MoE 30B-A3B)
  - Pick an NPU tier (LOW_LP4 … HIGH) or select RTX 5090 reference
  - Pick a workload profile (short_chat, rag_qa, long_decode,
    meeting_summarization, agentic_roundtrip)
  - Tune a compiler-quality slider (0.5–1.0)
  - See measured (green badge) or BW-projected (yellow badge) numbers.

Password gate via st.secrets['PASSWORD']. Data source: sizer/sizer_bundle.json
(regenerated by personal-ai-framework's eval/build_sizer_bundle.py).
"""
from __future__ import annotations

import io

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from sizer.measured import get_bundle_summary
from sizer.npu_model import MODELS, TIERS, project_llm, model_active_bytes_per_token
from sizer.precision import (
    MEASURED_PRECISION_QUALITY, MEASURED_PRECISION_SPEED,
    tier_precision_capability, capability_badge, capability_label,
    capability_color, quality_badge_text, quality_color,
    RETARGETING_COSTS, deployment_path_for_tier, retargeting_cost_color,
    REGRESSION_RIGOR, gates_per_cycle, annualized_testing_cost,
)


st.set_page_config(page_title="Skippy NPU Sizer", layout="wide",
                   initial_sidebar_state="expanded")


# ───────────────────────── Password gate ─────────────────────────

def _gate() -> bool:
    want = st.secrets.get("PASSWORD") if hasattr(st, "secrets") else None
    if not want:
        return True  # no gate configured
    if st.session_state.get("_ok"):
        return True
    with st.form("login"):
        pw = st.text_input("Password", type="password", key="pw_input")
        if st.form_submit_button("Enter"):
            if pw == want:
                st.session_state["_ok"] = True
                st.rerun()
            else:
                st.error("Incorrect.")
    return False


if not _gate():
    st.stop()


# ───────────────────────── Workload profile metadata ─────────────────────────

# What-if prompt/decode shapes per workload profile. Mirrors the targets in
# eval/sizer_workload_profiles.json (personal-ai-framework). Users adjust
# these knobs in the sidebar; defaults match the profile's target shape.
WORKLOAD_DEFAULTS = {
    "short_chat":             {"prompt_tokens": 750,  "decode_tokens": 150,  "label": "Short chat — no RAG, conversational"},
    "rag_qa":                 {"prompt_tokens": 4800, "decode_tokens": 400,  "label": "RAG Q&A — retrieved context 5–10 chunks"},
    "long_decode":            {"prompt_tokens": 2800, "decode_tokens": 2500, "label": "Long-decode doc gen — spec / proposal"},
    "meeting_summarization":  {"prompt_tokens": 12700,"decode_tokens": 800,  "label": "Meeting summarization — 30–60 min transcript"},
    "agentic_roundtrip":      {"prompt_tokens": 2500, "decode_tokens": 200,  "label": "Agentic roundtrip — single tool-loop iteration"},
}


# ───────────────────────── Sidebar ─────────────────────────

with st.sidebar:
    st.header("Skippy NPU Sizer")

    st.caption("What-if perf model for Skippy on different NPU tiers. "
               "Measured baseline: RTX 5090 bake-offs from "
               "personal-ai-framework `eval/run_sizer_bakeoffs.py`.")

    model_keys = list(MODELS.keys())
    model_key = st.selectbox(
        "Model",
        options=model_keys,
        format_func=lambda k: MODELS[k]["display_name"],
        index=model_keys.index("qwen3-30b-a3b-q4-moe"),
        key="k_model",
        help="MoE decode tok/s scales with active params (~3B) not total "
             "params (~30B). Dense 14B moves ~5× more bytes per decoded token.",
    )

    tier_keys = list(TIERS.keys())
    tier_name = st.selectbox(
        "NPU Tier",
        options=tier_keys,
        index=tier_keys.index("NPU Mid"),
        key="k_tier",
        help="RTX 5090 shows measured Skippy data. All NPU tiers project "
             "from the 5090 baseline by effective-bandwidth ratio.",
    )
    hw = TIERS[tier_name]

    workload_keys = list(WORKLOAD_DEFAULTS.keys())
    workload_id = st.selectbox(
        "Workload profile",
        options=workload_keys,
        format_func=lambda k: WORKLOAD_DEFAULTS[k]["label"],
        index=0,
        key="k_workload",
    )

    with st.expander("Per-workload token shape", expanded=False):
        wd = WORKLOAD_DEFAULTS[workload_id]
        prompt_tokens = st.number_input(
            "Prompt tokens",
            min_value=10, max_value=128000,
            value=wd["prompt_tokens"], step=100,
            key=f"k_pt_{workload_id}",
        )
        decode_tokens = st.number_input(
            "Decode tokens",
            min_value=1, max_value=8000,
            value=wd["decode_tokens"], step=50,
            key=f"k_dt_{workload_id}",
        )

    compiler_quality = st.slider(
        "Compiler quality",
        min_value=0.5, max_value=1.0, value=1.0, step=0.05,
        key="k_compiler",
        help="How well the target NPU's compiler stack matches NVIDIA's mature "
             "CUDA path. 1.0 = parity; 0.5 = half the throughput at same BW. "
             "Only applied to projected tiers, not measured.",
    )

    with st.expander("About this sizer", expanded=False):
        bs = get_bundle_summary()
        st.caption(
            f"Bundle generated: {bs['bundle_meta'].get('generated_at','?')}\n\n"
            f"Models measured: {len(bs['models'])}\n\n"
            f"Source bake-offs: see `sizer_bundle.json` meta."
        )


# ───────────────────────── Main page ─────────────────────────

st.title(MODELS[model_key]['display_name'])
st.markdown(f"**Tier:** {tier_name}  &nbsp;·&nbsp;  **Workload:** "
            f"_{WORKLOAD_DEFAULTS[workload_id]['label']}_  &nbsp;·&nbsp;  "
            f"{prompt_tokens:,} prompt / {decode_tokens:,} decode tokens")


# Project the selected cell
try:
    r = project_llm(
        model_key, hw, workload_id,
        prompt_tokens=prompt_tokens,
        decode_tokens=decode_tokens,
        compiler_quality=compiler_quality,
    )
    err = None
except ValueError as e:
    r, err = None, str(e)

if err:
    st.warning(
        f"**No measurement yet for this cell.** Run "
        f"`eval/run_sizer_bakeoffs.py` against a Skippy instance, "
        f"regenerate `sizer_bundle.json`, and redeploy. Detail: {err}"
    )
    st.stop()

# Source badge — feasibility first (model can't even load), then measured/projected.
if r["source"] == "wont_fit":
    f = r["feasibility"]
    st.error(
        f"🔴 **Won't fit — model exceeds NPU memory capacity.**\n\n"
        f"Required: {f['required_gb']} GB "
        f"(weights {f['breakdown']['weights_gb']} + KV {f['breakdown']['kv_cache_gb']} "
        f"+ overhead {f['breakdown']['overhead_gb']}) · "
        f"Available: {f['available_gb']} GB · "
        f"Short by **{-f['headroom_gb']:.1f} GB**.\n\n"
        f"This NPU tier cannot load this model. Try a smaller model "
        f"(e.g. TinyLlama 1.1B Q4 ≈ 0.7 GB, Qwen 1.5B Q4 ≈ 1.0 GB) or "
        f"move up to a tier with enough memory."
    )
    st.stop()

if r["source"] == "dtype_mismatch":
    d = r["dtype_detail"]
    st.error(
        f"🔴 **Dtype incompatible — this NPU can't execute the model's compute path.**\n\n"
        f"Model needs: **{d['model_needs']}** (weights are {d['quant_scheme']} "
        f"but matmul runs in fp16 — standard llama-cpp behavior).\n\n"
        f"This NPU supports: **{', '.join(d['hw_supports'])}**.\n\n"
        f"To run on this silicon class you'd need either: "
        f"(a) re-quantize to **W8A8** (weights AND activations INT8), "
        f"(b) fall back to **CPU fp16** (unusable — sub-1 tok/s at 14B dense), "
        f"or (c) move up to a tier with fp16/bf16 tensor support "
        f"(NPU Low-LP5X or higher)."
    )
    st.stop()

if r["source"] == "measured":
    st.success(f"🟢 **Measured** on RTX 5090 — direct bake-off baseline")
else:
    feas_note = ""
    if r["feasibility"]["verdict"] == "tight":
        feas_note = (f"  ⚠️ _Tight fit_ — only "
                     f"{r['feasibility']['headroom_gb']} GB headroom "
                     f"({r['feasibility']['required_gb']} GB needed of "
                     f"{r['feasibility']['available_gb']} GB).")
    st.info(f"🟡 **Projected** — BW-scaled from RTX 5090 reference. "
            f"Effective-bandwidth ratio: {hw.effective_bandwidth_gbs / 1523.2:.3f}."
            f"{feas_note}")

# Top-line numeric metrics
c1, c2, c3, c4 = st.columns(4)
c1.metric("Decode tok/s", f"{r['decode_tok_s']:.1f}")
c2.metric("Prefill tok/s", f"{r['prefill_tok_s']:.0f}")
c3.metric("Total latency", f"{r['total_s']:.2f} s")
c4.metric("Decode portion", f"{r['decode_s']:.2f} s")

st.markdown("---")


# ───────────────────────── Precision capability card ─────────────────────────
# What compute precisions can this tier actually execute, and what's the
# measured quality delta for each? Populated from Skippy's 2026-04-23 Qwen
# 2.5 14B quantization experiments — fp16/FP8 on A6000 pod, INT8 on H100 pod,
# Q4_K_M on Skippy's native-RAG 5090 run (methodology-different, shown for
# context).

st.subheader("Precision capability")
st.caption(
    f"What compute precisions **{hw.name}** can execute, and the measured "
    f"quality delta for each precision on Qwen 2.5 14B / Skippy's v2+RAG eval "
    f"(44 prompts × 3 samples). Green = within ~2pp noise floor; "
    f"amber = small but real; red = meaningful regression."
)

_cap = tier_precision_capability(hw.name)
# Present 4 precision columns: bf16/fp16, FP8, INT8, Q4_K_M
_precision_columns = [
    ("bf16/fp16", "fp16",  "fp16/bf16"),
    ("fp8",       "fp8",   "FP8"),
    ("int8",      "int8",  "INT8 (W8A8)"),
    ("q4_km",     "q4_km", "Q4_K_M"),
]
_cols = st.columns(4)
for col, (cap_key, quality_key, display) in zip(_cols, _precision_columns):
    cap_level = _cap.get(cap_key, "none")
    pm = MEASURED_PRECISION_QUALITY.get(quality_key)
    speed = MEASURED_PRECISION_SPEED.get(quality_key)

    # Top row: precision name + capability glyph, color-coded
    cap_color = capability_color(cap_level)
    cap_glyph = capability_badge(cap_level)
    cap_text = capability_label(cap_level)
    with col:
        st.markdown(
            f"<div style='padding: 10px; border-radius: 6px; "
            f"background:#1f2937; border-left: 4px solid {cap_color};'>"
            f"<div style='font-size: 0.85rem; color: #9ca3af;'>{display}</div>"
            f"<div style='font-size: 1.3rem; color: {cap_color}; font-weight: 600;'>"
            f"{cap_glyph} {cap_text}</div>"
            + (
                f"<div style='font-size: 0.8rem; color: {quality_color(pm)}; "
                f"margin-top: 6px;'>Quality: {quality_badge_text(pm)}</div>"
                if pm is not None and cap_level != "none" else
                f"<div style='font-size: 0.8rem; color: #6b7280; margin-top: 6px;'>"
                f"Quality: —</div>"
            )
            + (
                f"<div style='font-size: 0.8rem; color: #9ca3af; margin-top: 4px;'>"
                f"Speed (5090): {speed['tok_s']:.1f} tok/s "
                f"({speed['speedup_vs_fp16']:.2f}× fp16)</div>"
                if speed is not None and cap_level != "none" else ""
            )
            + "</div>",
            unsafe_allow_html=True,
        )

with st.expander("How to read this / what was measured", expanded=False):
    st.markdown("""
**Capability glyphs:**
- ✓ **tensor-core** — native tensor-core matmul path (fast, preferred)
- ⚠︎ **CUDA-core only** — legacy CUDA-core path (e.g. DP4A); works for
  small CNNs but crippling for LLM-scale matmul
- ✗ **not supported** — no hardware path; would need CPU fallback or
  a different model quantization scheme

**Quality colors** (delta vs fp16 on Skippy's v2+RAG eval, 132 samples):
- 🟢 **within ±2pp** — indistinguishable from fp16 (noise floor)
- 🟡 **2–5pp** — small but real drift; inspect per-category breakdown
- 🔴 **>5pp** — meaningful capability regression; reconsider the precision

**Why INT8 is CUDA-core-only on 5090 but tensor-core on every NPU tier:**
consumer Blackwell (SM120) dropped dedicated tensor-core INT8 in favor of
FP8/FP4 tensor cores. INT8 math still works on 5090 via the DP4A CUDA-core
path (retained from Pascal) — vLLM's CUTLASS W8A8 loader refuses the 5090
because it requires tensor-core INT8 templates. Edge NPUs (NXP Neutron,
Kinara Ara, Hailo-8 class) have dedicated INT8 matmul engines and don't
share this constraint.

**INT8 measured -3.8pp caveat:** the 5 regressed samples are all on two
refuse-to-answer prompts where both fp16 and INT8 correctly refused.
INT8's hedge used family-level chip names ("various NXP i.MX processors")
while fp16's hedge named specific SKUs ("NXP i.MX 8QuadMax"). Content
is equivalent; only the keyword-match grader sees a difference.

**Q4_K_M quality is from a different methodology** (Skippy's native RAG
path via llama-cpp) and isn't directly comparable to the fp16/FP8/INT8
shim-path measurements. Shown as context, not as a head-to-head delta.

**Measurement provenance:**
- fp16 + FP8: A6000 48GB pod, vLLM shim, v2+RAG (2026-04-23 FP8 runbook)
- INT8 W8A8: H100 80GB SXM pod, SmoothQuant+GPTQ 512 calib, same shim
- Q4_K_M: RTX 5090 local, Skippy's native RAG pipeline
""")

st.markdown("---")


# ───────────────────────── Retargeting cost ─────────────────────────
# The lifecycle cost of deploying a model to a tier that can't run the
# model's native precision. This is per-iteration — every time the model
# retrains, this cost fires again.

st.subheader("Retargeting cost per model revision")
st.caption(
    f"Lifecycle cost of shipping Skippy's current Q4_K_M fp16-compute model to "
    f"**{hw.name}** on each retrain. The silicon team's \"area savings from "
    f"INT8-only\" is a one-time BOM win; this is the forever-cost at the "
    f"org level — paid every time the model is retrained, per customer, "
    f"per fine-tune."
)

# Figure out which retargeting path this tier needs for Skippy's current model
_skippy_model_dtype = MODELS[model_key].get("compute_dtype", "fp16")
_path_key = deployment_path_for_tier(hw.name, _skippy_model_dtype)
_cost = RETARGETING_COSTS[_path_key]
_cost_color = retargeting_cost_color(_path_key)

_rc_col_a, _rc_col_b, _rc_col_c, _rc_col_d = st.columns(4)
with _rc_col_a:
    st.markdown(
        f"<div style='padding: 10px; border-radius: 6px; background:#1f2937; "
        f"border-left: 4px solid {_cost_color};'>"
        f"<div style='font-size: 0.8rem; color: #9ca3af;'>Deployment path</div>"
        f"<div style='font-size: 1.05rem; color: {_cost_color}; font-weight: 600;'>"
        f"{_cost.path}</div>"
        f"</div>",
        unsafe_allow_html=True,
    )
_rc_col_b.metric("Wall time per cycle", f"{_cost.wall_minutes} min")
_rc_col_c.metric("Compute cost per cycle", f"${_cost.dollars_per_cycle:.2f}")
_rc_col_d.metric("Engineer hours per cycle", f"{_cost.engineer_hours:.1f} hrs")

# Annualized what-if: user picks retrain cadence + regression-testing
# rigor, we project annualized overhead with Gate A / Gate B split.
with st.expander("Annualized lifecycle cost — retrain cadence + testing rigor",
                 expanded=False):
    _cad_col, _rig_col = st.columns(2)
    with _cad_col:
        _retrain_freq = st.selectbox(
            "How often does Skippy retrain?",
            options=["daily", "weekly", "monthly", "quarterly", "annually"],
            index=1,
            key="k_retrain_freq",
            help="Pick the retrain cadence. The sizer multiplies per-cycle "
                 "cost by the matching cycles-per-year to project annual "
                 "overhead.",
        )
    with _rig_col:
        _rigor_key = st.selectbox(
            "Regression testing rigor",
            options=list(REGRESSION_RIGOR.keys()),
            format_func=lambda k: REGRESSION_RIGOR[k].display_name,
            index=0,
            key="k_rigor",
            help="How thorough is the regression suite run on each retrain? "
                 "Smoke approximates today's 44-prompt harness. Nightly is "
                 "the floor for serious production. Pre-release adds human "
                 "red-team and domain-expert review.",
        )
    cycles_per_year = {
        "daily": 365, "weekly": 52, "monthly": 12,
        "quarterly": 4, "annually": 1,
    }[_retrain_freq]
    _rigor = REGRESSION_RIGOR[_rigor_key]

    # Compute Gate A / Gate B breakdown for this (path, rigor, cadence)
    _testing = annualized_testing_cost(_path_key, _rigor_key, cycles_per_year)
    _gates = gates_per_cycle(_path_key)

    # Alt-path (counterfactual) for the comparison story
    _alt_path_key = "ptq" if _path_key == "fp_native" else "fp_native"
    _alt_testing = annualized_testing_cost(_alt_path_key, _rigor_key,
                                           cycles_per_year)

    # Counterfactual cost shock FIRST — what the choice WOULD cost on the
    # other precision-path at this rigor tier
    if _path_key == "fp_native":
        st.markdown(
            f"**If this were an INT8-only tier** (LP4 / LP5-32bit / LP5-64bit) "
            f"and you had to run both Gate A (training-validation) AND Gate B "
            f"(quant-validation) at **{_rigor.display_name.split(' (')[0]}** "
            f"rigor, **{_retrain_freq}** cadence ({cycles_per_year} cycles/yr):"
        )
        _cmp_a, _cmp_b, _cmp_c = st.columns(3)
        _cmp_a.metric("Annual engineer time",
                      f"{_alt_testing['total_engineer_hours']:.0f} hrs")
        _cmp_b.metric("Annual compute cost",
                      f"${_alt_testing['total_dollars']:,.0f}")
        _cmp_c.metric("Annual wall time on pod",
                      f"{_alt_testing['total_wall_hours']:.0f} hrs")
        st.caption(
            f"Breakdown: Gate A = {_alt_testing['gate_a']['invocations']} "
            f"invocations @ ${_rigor.dollars_per_gate:.0f}/gate = "
            f"${_alt_testing['gate_a']['dollars']:,.0f}. "
            f"Gate B = {_alt_testing['gate_b']['invocations']} invocations @ "
            f"${_rigor.dollars_per_gate:.0f}/gate = "
            f"${_alt_testing['gate_b']['dollars']:,.0f}. "
            f"**Gate B is the silicon-choice delta.**"
        )
    else:
        _savings_dollars = _alt_testing['total_dollars'] - _testing['total_dollars']
        _savings_hours = _alt_testing['total_engineer_hours'] - _testing['total_engineer_hours']
        st.markdown(
            f"**If you picked an FP-native tier instead** "
            f"(LP5X / Mid / High / 5090) at the same rigor + cadence, "
            f"you'd avoid Gate B entirely. Savings:"
        )
        _cmp_a, _cmp_b, _cmp_c = st.columns(3)
        _cmp_a.metric("Engineer hrs saved", f"{_savings_hours:.0f} hrs")
        _cmp_b.metric("Compute cost saved", f"${_savings_dollars:,.0f}")
        _cmp_c.metric("Gate B invocations avoided",
                      f"{_testing['gate_b']['invocations']:.0f}")

    st.markdown("---")

    # Your actual tier at this rigor + cadence, with Gate A/B breakdown
    st.markdown(
        f"**Your actual cost** at **{_rigor.display_name.split(' (')[0]}** "
        f"rigor, **{_retrain_freq}** cadence, shipping to **{hw.name}**:"
    )
    _ann_a, _ann_b, _ann_c = st.columns(3)
    _ann_a.metric("Annual engineer time",
                  f"{_testing['total_engineer_hours']:.0f} hrs")
    _ann_b.metric("Annual compute cost",
                  f"${_testing['total_dollars']:,.0f}")
    _ann_c.metric("Annual wall time on pod",
                  f"{_testing['total_wall_hours']:.0f} hrs")

    # Gate A / Gate B breakdown table
    st.caption("Gate breakdown (which tests fire on each retrain):")
    _gate_rows = [
        {
            "Gate": "**A** — \"did the new training do what we wanted?\"",
            "Invocations/yr": _testing['gate_a']['invocations'],
            "Engineer hrs/yr": f"{_testing['gate_a']['engineer_hours']:.0f}",
            "Compute $/yr": f"${_testing['gate_a']['dollars']:,.0f}",
            "Required on": "every path (FP-native + INT8)",
        },
        {
            "Gate": "**B** — \"did quantization damage anything Gate A validated?\"",
            "Invocations/yr": _testing['gate_b']['invocations'],
            "Engineer hrs/yr": f"{_testing['gate_b']['engineer_hours']:.0f}",
            "Compute $/yr": f"${_testing['gate_b']['dollars']:,.0f}",
            "Required on": "INT8-only silicon only",
        },
    ]
    st.dataframe(pd.DataFrame(_gate_rows), width="stretch", hide_index=True)

    if _rigor.human_review:
        st.warning(
            f"⚠️ **Human red-team / domain-expert review required at "
            f"{_rigor.display_name.split(' (')[0]} rigor.** The "
            f"{_testing['total_engineer_hours']:.0f} engineer-hrs/year "
            f"above includes ~{0.3 * _testing['total_engineer_hours']:.0f} "
            f"hrs of senior-engineer / domain-specialist time that can't be "
            f"automated away. Calendar time per release: 1-2 weeks."
        )
    elif _cost.regression_gate:
        st.warning(
            f"⚠️ **Regression gate required** — this path runs both Gate A "
            f"and Gate B before shipping. Factor release-blocking risk: "
            f"~10-20% of quant cycles need a re-tune pass (different calib "
            f"data, different scheme parameters), which doubles Gate B cost "
            f"when it fires."
        )
    else:
        st.success(
            f"🟢 **No Gate B on this tier — only Gate A fires.** Deploy the "
            f"FP-native training artifact directly. The silicon-choice "
            f"delta between this tier and an INT8-only tier at the same "
            f"rigor is **${_alt_testing['total_dollars'] - _testing['total_dollars']:,.0f}/yr "
            f"+ {_alt_testing['total_engineer_hours'] - _testing['total_engineer_hours']:.0f} engineer-hrs/yr**."
        )

    with st.expander(f"What \"{_rigor.display_name.split(' (')[0]}\" "
                     f"rigor actually covers", expanded=False):
        st.markdown(f"**Tier:** {_rigor.display_name}")
        st.markdown(f"**Test count:** {_rigor.test_count}")
        st.markdown(f"**Per-gate cost:** ~${_rigor.dollars_per_gate:.0f} + "
                    f"{_rigor.engineer_hours_per_gate:.1f} engineer hrs + "
                    f"{_rigor.wall_hours_per_gate:.1f} wall hrs")
        st.markdown(f"**Human review:** "
                    f"{'required' if _rigor.human_review else 'not required'}")
        st.markdown(f"**Notes:** {_rigor.notes}")

with st.expander("Why this cost exists — the hidden silicon trade-off",
                 expanded=False):
    st.markdown(f"""
**What we're measuring:** {_cost.notes}

**The four-rung ladder of retargeting cost:**

| Path | Per-cycle wall | Per-cycle $ | Per-cycle engineer hrs | Regression gate? |
|---|---:|---:|---:|:---:|
| **FP-native** (same precision as trained) | 0 min | $0 | 0 hrs | no |
| **Weight-only quant** (Q4_K_M / Q8_0) | ~5 min | $0 | 0.1 hrs | no |
| **PTQ W8A8 INT8** (what we ran today) | ~55 min | ~$1.75 | ~1.5 hrs | **yes** |
| **Quantization-aware training** | 4-8 hrs | $30-100 | ~4 hrs | **yes** |

**What this means for the architecture decision:**

- INT8-only silicon forces either **PTQ** (every retrain = 55-minute pod job
  + 1.5 engineer hrs + human signoff) or **QAT** (multiply by 10). This is
  **paid forever**, not once.
- FP-native silicon (bf16/FP8) lets you ship the training artifact directly.
  Zero retargeting cost per cycle.
- For a model that retrains weekly (Skippy's current pattern), INT8-only
  silicon adds **~75-80 engineer-hours/year + $90/year in compute** just
  for the quant-regression gate. For a product line with N customer
  fine-tunes, multiply by N.
- For a frozen-model consumer device, this cost is negligible. For a
  platform that supports continuous fine-tuning or customer-specific
  model customization, it's often **larger than the BOM savings from
  the cheaper INT8-only silicon**.

**The missing row in most silicon-team trade matrices:**
→ Per-unit BOM cost is a ONE-TIME win (factored into gross margin)
→ Per-retrain retargeting cost is a RECURRING expense (factored into
   OPEX, engineer time, and release velocity)

A rigorous silicon decision needs both rows.
""")

st.markdown("---")

# Per-stage breakdown bar chart
stage_ms = {
    "Host (retrieval + agent)": r["host_ms"],
    "Prefill": r["prefill_s"] * 1000,
    "Decode": r["decode_s"] * 1000,
}
fig = go.Figure()
fig.add_trace(go.Bar(
    x=list(stage_ms.keys()),
    y=list(stage_ms.values()),
    text=[f"{v:,.0f} ms" for v in stage_ms.values()],
    textposition="outside",
    marker_color=["#6b7280", "#3b82f6", "#10b981"],
))
import math
_ymax = max(stage_ms.values())
fig.update_layout(
    title=f"Per-stage time — {MODELS[model_key]['display_name']} / {tier_name}",
    yaxis_title="Milliseconds (log)",
    yaxis_type="log",
    # Log-scale range: from 1ms to 1 decade above the tallest bar, so the
    # "outside" text labels don't clip against the top edge.
    yaxis=dict(gridcolor="#374151",
               range=[0, math.log10(max(_ymax, 10)) + 0.6]),
    height=420,
    margin=dict(t=60, b=40, l=40, r=20),
    plot_bgcolor="#1f2937",
    paper_bgcolor="#111827",
    font=dict(color="#f3f4f6"),
    xaxis=dict(showgrid=False),
)
st.plotly_chart(fig, width="stretch")


# Cross-tier comparison table
st.subheader("Cross-tier comparison")
st.caption(f"All tiers projected from RTX 5090's measured baseline for "
           f"**{MODELS[model_key]['display_name']}** at **{WORKLOAD_DEFAULTS[workload_id]['label']}**. "
           "Lower tier → more bandwidth-bound → slower decode.")
rows = []
for tname, thw in TIERS.items():
    try:
        rr = project_llm(
            model_key, thw, workload_id,
            prompt_tokens=prompt_tokens,
            decode_tokens=decode_tokens,
            compiler_quality=compiler_quality,
        )
        if rr["source"] == "wont_fit":
            f = rr["feasibility"]
            rows.append({
                "Tier": tname,
                "Source": "🔴 won't fit",
                "Decode tok/s": "—",
                "Prefill tok/s": "—",
                "Total (s)": "—",
                "Host (ms)": f"needs {f['required_gb']} GB (has {f['available_gb']})",
            })
            continue
        if rr["source"] == "dtype_mismatch":
            d = rr["dtype_detail"]
            rows.append({
                "Tier": tname,
                "Source": "🔴 dtype mismatch",
                "Decode tok/s": "—",
                "Prefill tok/s": "—",
                "Total (s)": "—",
                "Host (ms)": f"needs {d['model_needs']} (has {'/'.join(d['hw_supports'])})",
            })
            continue
        tight_note = " ⚠️" if rr["feasibility"]["verdict"] == "tight" else ""
        rows.append({
            "Tier": tname,
            "Source": ("🟢 measured" if rr["source"] == "measured"
                       else "🟡 projected") + tight_note,
            "Decode tok/s": rr["decode_tok_s"],
            "Prefill tok/s": round(rr["prefill_tok_s"]),
            "Total (s)": rr["total_s"],
            "Host (ms)": rr["host_ms"],
        })
    except ValueError:
        rows.append({"Tier": tname, "Source": "⚪ no data"})
df = pd.DataFrame(rows)
st.dataframe(df, width="stretch", hide_index=True)


# Cross-model comparison on this tier
st.subheader("Cross-model comparison (on this tier)")
st.caption("MoE's decode advantage comes from fewer active params per token — "
           "dense 14B moves ~4.5× more weight bytes per decoded token than MoE 30B-A3B.")
rows2 = []
for mk in MODELS:
    try:
        rr = project_llm(
            mk, hw, workload_id,
            prompt_tokens=prompt_tokens,
            decode_tokens=decode_tokens,
            compiler_quality=compiler_quality,
        )
        if rr["source"] == "wont_fit":
            rows2.append({
                "Model": MODELS[mk]["display_name"],
                "Arch": "MoE" if MODELS[mk]["is_moe"] else "dense",
                "Active params (B)": round(MODELS[mk]["active_params"] / 1e9, 1),
                "Bytes/token decode (B)": round(model_active_bytes_per_token(mk) / 1e9, 2),
                "Decode tok/s": "—",
                "Total (s)": "—",
                "Source": "🔴 won't fit",
            })
            continue
        if rr["source"] == "dtype_mismatch":
            rows2.append({
                "Model": MODELS[mk]["display_name"],
                "Arch": "MoE" if MODELS[mk]["is_moe"] else "dense",
                "Active params (B)": round(MODELS[mk]["active_params"] / 1e9, 1),
                "Bytes/token decode (B)": round(model_active_bytes_per_token(mk) / 1e9, 2),
                "Decode tok/s": "—",
                "Total (s)": "—",
                "Source": "🔴 dtype mismatch",
            })
            continue
        rows2.append({
            "Model": MODELS[mk]["display_name"],
            "Arch": "MoE" if MODELS[mk]["is_moe"] else "dense",
            "Active params (B)": round(MODELS[mk]["active_params"] / 1e9, 1),
            "Bytes/token decode (B)": round(model_active_bytes_per_token(mk) / 1e9, 2),
            "Decode tok/s": rr["decode_tok_s"],
            "Total (s)": rr["total_s"],
            "Source": ("🟢 measured" if rr["source"] == "measured"
                       else "🟡 projected") + (" ⚠️" if rr["feasibility"]["verdict"] == "tight" else ""),
        })
    except ValueError:
        rows2.append({"Model": MODELS[mk]["display_name"], "Source": "⚪ no data"})
df2 = pd.DataFrame(rows2)
st.dataframe(df2, width="stretch", hide_index=True)


# XLSX download
st.markdown("---")
buf = io.BytesIO()
with pd.ExcelWriter(buf, engine="openpyxl") as xlw:
    df.to_excel(xlw, sheet_name="cross_tier", index=False)
    df2.to_excel(xlw, sheet_name="cross_model", index=False)
st.download_button(
    "⬇ Download projections (XLSX)",
    data=buf.getvalue(),
    file_name=f"skippy_sizer_{model_key}_{tier_name.replace(' ','_')}_{workload_id}.xlsx",
    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
)


# Measured provenance panel
with st.expander("Measured data provenance", expanded=False):
    bs = get_bundle_summary()
    st.write("**Bundle metadata**")
    st.json(bs["bundle_meta"])
    st.write("**Per-model measured workloads**")
    st.json(bs["workloads_per_model"])
